vich_uploader:
    db_driver: orm

    mappings:
       cours:
           uri_prefix: /images/cours
           upload_destination: '%kernel.project_dir%/public/images/cours'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
