# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        media_uploads:
            uri_prefix:         /uploads/media
            upload_destination: '%kernel.project_dir%/public/uploads/media'
            namer: vich_uploader.namer_origname
